# Generated by Django 6.0.3 on 2026-04-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_views_post_comments_count_post_likes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmarks_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
