# Generated by Django 6.0.3 on 2026-05-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='group_engagement_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
