# Generated by Django 6.0.3 on 2026-05-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_image_message_shared_post_message_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='muted',
            field=models.BooleanField(default=False),
        ),
    ]
